apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: terraform-
spec:
  workflowTemplateRef:
    name: terraform
  entrypoint: update-auto-approve
  arguments:
    parameters:     
    - name: terraform-secret-name
      value: "tf-sandboxes"
