apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: idac-tf-
spec:
  podGC:
    # Pod GC strategy must be one of the following:
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    # Default: do not delete pods
    strategy: OnPodCompletion
    # The duration before pods in the GC queue get deleted. Defaults to 5s
    deleteDelayDuration: 86400s

  ttlStrategy:
    #The TTLStrategy sets the strategy for how long workflows that are
    # successful, not successful, or completed should live.
    secondsAfterCompletion: 60 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 60 # Time to live after workflow is successful
    secondsAfterFailure: 86400 # Time to live after workflow fails
  entrypoint: main
  serviceAccountName: "argo-workflow"
  # artifactGC:
  #   strategy: "OnWorkflowCompletion"
  #   serviceAccountName: "argo-workflows"

  arguments:
    parameters:
      - name: terraform-docker-image
        value: "ghcr.io/cisco-dcloud/argo-workflows-templates/terraform/terraform-runner:latest"
      - name: terraform-variables-user
        value: ""
      - name: terraform-variables-admin
        value: ""
      - name: terraform-parallelism
        value: "2"
      - name: terraform-debug-level
        value: "ERROR" #TRACE, DEBUG, INFO, WARN or ERROR
      - name: terraform-action
        value: "apply" #apply, destroy
      - name: terraform-files-s3-bucket
      - name: terraform-files-s3-key
      - name: pool-manager-reservation-id
      - name: pool-manager-resource-id

  nodeSelector:
    idac.cat-dcloud.com/nodegroup-name: prod
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "prod"
      effect: "NoSchedule"

  templates:
    - name: kubectl-curl-jq-scripts
      inputs:
        parameters:
          - name: commands
            value: ""
      metadata:
        labels:
          idac_request: "{{workflow.labels.idac_request}}" #The workflow label is appended by iDAC
      script:
        imagePullPolicy: "IfNotPresent"
        image: saagie/curl-jq-helm-kubectl:2311020942_1.25.12
        command: ["sh"]
        source: "{{inputs.parameters.commands}}"
        env:
          - name: POOLMANAGER_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{=workflow.namespace == 'idac' ? 'idac' : 'kitchen' }}"
                key: POOLMANAGER_TOKEN
      outputs:
        parameters:
          - name: output
            valueFrom:
              path: /tmp/outputs.logs
          - name: gcp-creds
            valueFrom:
              path: /tmp/service-account-key.json

    - name: terraformscript
      inputs:
        artifacts:
          - name: terraform-folder
            path: /home/terraform
        parameters:
          - name: gcp-creds
          - name: terraform-commands
            value: ""
      metadata:
        labels:
          idac_request: "{{workflow.labels.idac_request}}" #The workflow label is appended by iDAC
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: "{{inputs.parameters.terraform-commands}}"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS # name of env var
            value: "/tmp/service-account-key.json"
      outputs:
        parameters:
          - name: terraform-outputs
            valueFrom:
              path: /tmp/tf_outputs.json
            globalName: terraform-outputs
        artifacts:
          - name: terraform-folder
            path: /home/terraform
            archive:
              none: {}
            s3:
              key: "{{workflow.parameters.terraform-files-s3-key}}"
    - name: main
      dag:
        tasks:
          - name: "get-creds-from-pm"
            template: kubectl-curl-jq-scripts
            arguments:
              parameters:
                - name: commands
                  value: |
                    echo "POOLMANAGER_TOKEN: $POOLMANAGER_TOKEN" >> /tmp/outputs.logs
                    echo "POOLMANAGER_RESERVATION_ID: {{workflow.parameters.pool-manager-reservation-id}}" >> /tmp/outputs.logs
                    echo "POOLMANAGER_RESOURCE_ID: {{workflow.parameters.pool-manager-resource-id}}" >> /tmp/outputs.logs
                    curl -vvv -X GET -H 'accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer $POOLMANAGER_TOKEN" -d '{"borrowed_id":"{{workflow.parameters.pool-manager-reservation-id}}", "resource_id":"{{workflow.parameters.pool-manager-resource-id}}"}' http://fridgev2-stable.apps:8080/api/v2/resource > /tmp/pm-response.json
                    download=$?
                    if [ $download -ne 0 ]; then
                        echo "Failed to download the secret from poolmanager" >> /tmp/outputs.logs
                        exit $download
                    fi
                    cat /tmp/pm-response.json | jq -r  .attributes.credentials > /tmp/service-account-key.json
                    exit $?

          - name: "terraform"
            template: terraformscript
            depends: "get-creds-from-pm.Succeeded"
            arguments:
              artifacts:
                - name: terraform-folder
                  s3:
                    endpoint: s3.amazonaws.com
                    bucket: "{{workflow.parameters.terraform-files-s3-bucket}}"
                    key: "{{workflow.parameters.terraform-files-s3-key}}"
              parameters:
                - name: gcp-creds
                  value: "{{tasks.get-creds-from-pm.outputs.parameters.gcp-creds}}"
                - name: terraform-commands
                  value: |
                    cat <<-EOF > /tmp/service-account-key.json
                    {{tasks.get-creds-from-pm.outputs.parameters.gcp-creds}}
                    EOF
                    action="{{workflow.parameters.terraform-action}}"

                    if [ "$action" = "apply" ]; then
                    echo "Executing apply..."
                    cat <<-EOF > /home/terraform/terraform_user.tfvars
                    {{workflow.parameters.terraform-variables-user}}
                    EOF
                    cat <<-EOF > /home/terraform/terraform_admin.tfvars
                    {{workflow.parameters.terraform-variables-admin}}
                    EOF
                    cd /home/terraform/
                    export TF_LOG="{{workflow.parameters.terraform-debug-level}}"
                    export TF_LOG_PATH="/home/terraform/tf_{{workflow.parameters.terraform-action}}.log"
                    /bin/terraform init -input=false && /bin/terraform plan -parallelism={{workflow.parameters.terraform-parallelism}} -var-file="terraform_user.tfvars" -var-file="terraform_admin.tfvars" -input=false -no-color -out=tfclientsplan && /bin/terraform apply -input=false -parallelism={{workflow.parameters.terraform-parallelism}} -no-color tfclientsplan && /bin/terraform output -json > /tmp/tf_outputs.json && exit 0
                    exit 1
                    fi

                    if [ "$action" = "destroy" ]; then
                    echo "Executing destroy..."              
                    cd /home/terraform/
                    chmod 644 *.tf
                    chmod 644 .terraform.lock.hcl
                    chmod -R 755 .terraform
                    export TF_LOG="{{workflow.parameters.terraform-debug-level}}"
                    export TF_LOG_PATH="/home/terraform/tf_{{workflow.parameters.terraform-action}}.log"
                    /bin/terraform destroy -auto-approve -input=false -parallelism={{workflow.parameters.terraform-parallelism}} -no-color -var-file="terraform_user.tfvars" -var-file="terraform_admin.tfvars" && /bin/terraform output -json > /tmp/tf_outputs.json && exit 0
                    exit 1
                    fi
                - name: terraform-variables-user
                  value: "{{workflow.parameters.terraform-variables-user}}"
                - name: terraform-variables-admin
                  value: "{{workflow.parameters.terraform-variables-admin}}"
