apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: idac-tf-
spec:
  podGC:
    # Pod GC strategy must be one of the following:
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    # Default: do not delete pods
    strategy: OnPodCompletion
    # The duration before pods in the GC queue get deleted. Defaults to 5s
    deleteDelayDuration: 86400s

  ttlStrategy:
    #The TTLStrategy sets the strategy for how long workflows that are
    # successful, not successful, or completed should live.
    secondsAfterCompletion: 60  # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 60     # Time to live after workflow is successful
    secondsAfterFailure: 86400   # Time to live after workflow fails
  entrypoint: main
  serviceAccountName: "argo-workflow"
  # artifactGC:
  #   strategy: "OnWorkflowCompletion"
  #   serviceAccountName: "argo-workflows"

  arguments:
    parameters:
    - name: terraform-docker-image
      value: "hashicorp/terraform:1.4" 
    - name: terraform-variables-user
      value: ""
    - name: terraform-variables-admin
      value: ""   
    - name: terraform-parallelism
      value: "2"      
    - name: terraform-debug-level
      value: "ERROR"                          #TRACE, DEBUG, INFO, WARN or ERROR 
    - name: terraform-action
      value: "apply"                          #apply, destroy 
    # - name: artifact-gc-policy
    #   value: "OnWorkflowCompletion"             #Never, OnWorkflowDeletion, OnWorkflowCompletion 
    - name: terraform-files-s3-bucket
    - name: terraform-files-s3-key
    - name: aws-secret-name
      value: "aws-credentials"

  templates:

    - name: k8ssecret
      inputs:
        parameters:
        - name: k8s-commands
          value: ""
      metadata:
        labels:
          idac_request: "{{workflow.labels.idac_request}}"   #The workflow label is appended by iDAC 
      script:
        imagePullPolicy: "IfNotPresent"
        image: bitnami/kubectl
        command: ["sh"]
        source: |
          env > /tmp/nodes_outputs.json
          kubectl get secrets -n idac-kitchen-deployments >> /tmp/nodes_outputs.json
      outputs:
        parameters:
          - name: nodes
            valueFrom: 
              path: /tmp/nodes_outputs.json


    - name: terraformscript
      inputs:
        artifacts:
        - name: terraform-folder
          path: /home/terraform
        parameters:
        - name: terraform-commands
          value: ""
      metadata:
        labels:
          idac_request: "{{workflow.labels.idac_request}}"   #The workflow label is appended by iDAC 
      script:
        imagePullPolicy: "IfNotPresent"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: "{{inputs.parameters.terraform-commands}}" 
        env:
        - name: AWS_ACCESS_KEY_ID      # name of env var
          valueFrom:
            secretKeyRef:
              name: "{{workflow.parameters.aws-secret-name}}"           # name of k8s secret
              key: AWS_ACCESS_KEY_ID          # 'key' subcomponent of the secret
        - name: AWS_SECRET_ACCESS_KEY  
          valueFrom:
            secretKeyRef:
              name: "{{workflow.parameters.aws-secret-name}}"
              key: AWS_SECRET_ACCESS_KEY    
        - name: AWS_DEFAULT_REGION  
          valueFrom:
            secretKeyRef:
              name: "{{workflow.parameters.aws-secret-name}}"
              key: AWS_DEFAULT_REGION 
      outputs:
        parameters:
          - name: terraform-outputs
            valueFrom: 
              path: /tmp/tf_outputs.json
            globalName: terraform-outputs
        artifacts:
          - name: terraform-folder
            path: /home/terraform
            archive:
              none: {}
            s3:
              key: "{{workflow.parameters.terraform-files-s3-key}}"
            # artifactGC:
            #   strategy: "{{workflow.parameters.artifact-gc-policy}}"
              # serviceAccountName: "argo-workflows"
              # forceFinalizerRemoval: true

    - name: main
      dag:
        tasks:        

          - name: "k8s-create-secret"
            template: k8ssecret
            when: "{{=workflow.parameters['aws-secret-name'] != 'aws-credentials'}}"
            arguments:
              parameters:
              - name: k8s-commands
                value: ""

          - name: "tf-{{workflow.parameters.terraform-action}}"
            template: terraformscript
            dependencies: ["k8s-create-secret"]
            arguments:
              artifacts:
              - name: terraform-folder
                s3:
                  endpoint: s3.amazonaws.com
                  bucket: "{{workflow.parameters.terraform-files-s3-bucket}}"
                  key: "{{workflow.parameters.terraform-files-s3-key}}"
              parameters:
              - name: terraform-commands
                value: |
                  action="{{workflow.parameters.terraform-action}}"

                  if [ "$action" = "apply" ]; then
                  echo "Executing apply..."
                  cat <<-EOF > /home/terraform/terraform_user.tfvars
                  {{workflow.parameters.terraform-variables-user}}
                  EOF
                  cat <<-EOF > /home/terraform/terraform_admin.tfvars
                  {{workflow.parameters.terraform-variables-admin}}
                  EOF
                  cd /home/terraform/
                  export TF_LOG="{{workflow.parameters.terraform-debug-level}}"
                  export TF_LOG_PATH="/home/terraform/tf_{{workflow.parameters.terraform-action}}.log"
                  /bin/terraform init -input=false && /bin/terraform plan -parallelism={{workflow.parameters.terraform-parallelism}} -var-file="terraform_user.tfvars" -var-file="terraform_admin.tfvars" -input=false -no-color -out=tfclientsplan && /bin/terraform apply -input=false -parallelism={{workflow.parameters.terraform-parallelism}} -no-color tfclientsplan && /bin/terraform output -json > /tmp/tf_outputs.json && exit 0
                  exit 1
                  fi

                  if [ "$action" = "destroy" ]; then
                  echo "Executing destroy..."              
                  cd /home/terraform/
                  chmod 644 *.tf
                  chmod 644 .terraform.lock.hcl
                  chmod -R 755 .terraform
                  export TF_LOG="{{workflow.parameters.terraform-debug-level}}"
                  export TF_LOG_PATH="/home/terraform/tf_{{workflow.parameters.terraform-action}}.log"
                  /bin/terraform destroy -auto-approve -input=false -parallelism={{workflow.parameters.terraform-parallelism}} -no-color -var-file="terraform_user.tfvars" -var-file="terraform_admin.tfvars" && /bin/terraform output -json > /tmp/tf_outputs.json && exit 0
                  exit 1
                  fi
              - name: terraform-variables-user
                value: "{{workflow.parameters.terraform-variables-user}}"
              - name: terraform-variables-admin
                value: "{{workflow.parameters.terraform-variables-admin}}"

          - name: "k8s-delete-secret"
            template: k8ssecret
            dependencies: ["tf-{{workflow.parameters.terraform-action}}"]
            when: "{{=workflow.parameters['aws-secret-name'] == 'aws-credentials'}}"
            arguments:
              parameters:
              - name: k8s-commands
                value: ""

