apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: terraform-idac-
spec:
  entrypoint: main
  serviceAccountName: "argo-workflow"
  arguments:
    parameters:
    - name: terraform-docker-image
      value: "hashicorp/terraform:1.4"
    - name: terraform-script-repository
      value: "https://github.com/cisco-dcloud/argo-workflows-templates.git"
    - name: terraform-script-path
      value: "terraform_examples/idac_test_01"     
    - name: terraform-variables-user
      value: ""  
    - name: terraform-variables-admin
      value: ""   
    - name: terraform-parallelism
      value: "2"      

  templates:
    - name: outputs
      inputs:
        artifacts:
        - name: terraform-folder
          path: /home/current
      script:
        imagePullPolicy: "IfNotPresent"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: |
          cd /home/current
          chmod 666 tfclientsplan
          chmod 644 *.tf
          chmod 644 .terraform.lock.hcl
          chmod -R 755 .terraform
          /bin/terraform output -json > /tmp/tf_outputs.json
      outputs:
        parameters:
          - name: terraform-outputs
            valueFrom: 
              path: /tmp/tf_outputs.json

    - name: approve
      suspend: {}

    - name: terraformscript
      inputs:
        artifacts:
        - name: terraform-folder
          path: /home/terraform
        parameters:
        - name: terraform-commands
          value: ""
          
      script:
        imagePullPolicy: "IfNotPresent"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: "{{inputs.parameters.terraform-commands}}" 
        env:
        - name: TF_VAR_AWS_ACCESS_KEY_ID      # name of env var
          valueFrom:
            secretKeyRef:
              name: aws-credentials           # name of k8s secret
              key: AWS_ACCESS_KEY_ID          # 'key' subcomponent of the secret
        - name: TF_VAR_AWS_SECRET_ACCESS_KEY  
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY    
        - name: TF_VAR_AWS_DEFAULT_REGION  
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_DEFAULT_REGION 
      outputs:
        artifacts:
          - name: terraform-folder
            path: /home/work
            archive:
              none: {}

    - name: main
      dag:
        tasks:
          - name: init-plan-apply
            template: terraformscript
            arguments:
              artifacts:
              - name: terraform-folder
                git:
                  repo: "{{workflow.parameters.terraform-script-repository}}"
                  depth: 1
              parameters:
              - name: terraform-commands
                value: |
                  #mkdir /home/work && cp -r /home/terraform/{{workflow.parameters.terraform-script-path}}/. /home/work && cd /home/work 
                  
                  cd /home/terraform/{{workflow.parameters.terraform-script-path}}/

                  cat <<-EOF > /home/terraform/{{workflow.parameters.terraform-script-path}}/terraform_user.tfvars
                  {{workflow.parameters.terraform-variables-user}}
                  EOF

                  cat <<-EOF > /home/terraform/{{workflow.parameters.terraform-script-path}}/terraform_admin.tfvars
                  {{workflow.parameters.terraform-variables-admin}}
                  EOF

                  ls -la
                  pwd
                  /bin/terraform init -input=false
                  /bin/terraform plan -parallelism={{workflow.parameters.terraform-parallelism}} -var-file="terraform_user.tfvars" -var-file="terraform_admin.tfvars" -input=false -no-color -out=tfclientsplan
                  /bin/terraform apply -input=false -parallelism={{workflow.parameters.terraform-parallelism}} -no-color tfclientsplan
              - name: terraform-variables-user
                value: "{{workflow.parameters.terraform-variables-user}}"
              - name: terraform-variables-admin
                value: "{{workflow.parameters.terraform-variables-admin}}"

          - name: outputs
            template: outputs
            dependencies: [init-plan-apply]
            arguments:
              artifacts:
              - name: terraform-folder
                from: "{{tasks.init-plan-apply.outputs.artifacts.terraform-folder}}"
          - name: approve-destroy
            dependencies: [outputs]
            template: approve
          - name: destroy
            template: terraformscript
            dependencies: [approve-destroy]
            arguments:
              artifacts:
              - name: terraform-folder
                from: "{{tasks.init-plan-apply.outputs.artifacts.terraform-folder}}"
              parameters:
              - name: terraform-commands
                value: |

                  cd /home/terraform/{{workflow.parameters.terraform-script-path}}/

                  ls -la
                  pwd

                  #mkdir /home/work && cp -r  /home/terraform/. /home/work && cd /home/work && ls -la
                  chmod 644 *.tf
                  chmod 644 .terraform.lock.hcl
                  chmod -R 755 .terraform
                  /bin/terraform destroy -auto-approve -input=false -parallelism={{workflow.parameters.terraform-parallelism}} -no-color